--ALTERS
CREATE TABLE CREDFISCAL.NCM(
    ID numeric NOT NULL,
    DESCRICAO character varying(200),
    UNIDADE character varying(5),
    CONSTRAINT PK_NCM PRIMARY KEY (ID)
);

CREATE TABLE CREDFISCAL.DOCUMENTO(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NUMERONF BIGINT,
    CNPJ BIGINT,
    NOTA MEDIUMTEXT,
    CONSTRAINT PK_DOCUMENTO PRIMARY KEY (ID)
);

CREATE TABLE CREDFISCAL.DOCUMENTOITEM(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ID_DOCUMENTO BIGINT,
    ID_NCM BIGINT,
    DESCRICAO MEDIUMTEXT,
    CONSTRAINT PK_DOCUMENTOITEM PRIMARY KEY (ID),
    FOREIGN KEY (ID_DOCUMENTO) REFERENCES CREDFISCAL.DOCUMENTO(ID)
);

CREATE TABLE CREDFISCAL.DOCUMENTOITEMRESULT(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ID_DOCUMENTOITEM BIGINT,
    DESCRICAO MEDIUMTEXT,
    CONSTRAINT PK_DOCUMENTOITEMRESULT PRIMARY KEY (ID),
    FOREIGN KEY (ID_DOCUMENTOITEM) REFERENCES CREDFISCAL.DOCUMENTOITEM(ID)
);

SELECT * 
  FROM CREDFISCAL.DOCUMENTO DOC
  JOIN CREDFISCAL.DOCUMENTOITEM DOCI ON DOCI.ID_DOCUMENTO = DOC.ID
  JOIN CREDFISCAL.DOCUMENTOITEMRESULT DOCR ON DOCR.ID_DOCUMENTOITEM = DOCI.ID

